---

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-iam-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-iam-authenticator
data:
  config.yaml: |
    clusterID: {{ .Values.clusterId }}
    server:
      mapRoles:
      - roleARN: {{ .Values.auth.adminRole }}
        username: kubernetes-admin
        groups:
        - system:masters

---
