---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
spec:
  ports:
    - name: http-metrics
      targetPort: 9100
      port: 9100
  selector:
    app: node-exporter