---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  {{- if eq (typeOf .Values.tcpServices) "map[string]interface {}" }}
  {{- range $key, $value := .Values.tcpServices }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  {{- if eq (typeOf .Values.udpService) "map[string]interface {}" }}
  {{- range $key, $value := .Values.udpServices }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{ end }}

---
