---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: prometheus-rules
data:
  scrape.rules: |-
    {{ $.Files.Get "static-files/scrape-rules.yaml" | nindent 4 }}
  alert.rules: |-
    {{ $.Files.Get "static-files/alert-rules.yaml" | nindent 4 }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: prometheus-config
data:
  prometheus.yml: |-
    {{ $.Files.Get "static-files/prometheus.yaml" | nindent 4 }}