---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: prometheus
  annotations:
    prometheus.io/scrape: "false"
  labels:
    app: prometheus
spec:
  ports:
    - name: http-client
      targetPort: 9090
      port: 9090
  selector:
    app: prometheus