---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ $.Release.Namespace }}
  name: prometheus
  labels:
    version: v{{ $.Chart.AppVersion }}
    app: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        version: v{{ $.Chart.AppVersion }}
        app: prometheus
    spec:
      priorityClassName: system-cluster-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.metal-city.ru/scope
                    operator: In
                    values:
                      - commom
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 9090
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.26.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
            - "--storage.tsdb.no-lockfile"
            - "--storage.tsdb.retention.time=3d"
            - "--storage.tsdb.retention.size=5GB"
          ports:
            - name: http-client
              containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: prometheus-rules
              mountPath: /etc/prometheus-rules
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometeus-data
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
        - name: prometeus-data
          persistentVolumeClaim:
            claimName: prometheus-data