image: alpine:3.4

stages:
  - Revision
  - Cluster
  - Workload

Plan Cluster Changes:
  stage: Revision
  image: alpine/terragrunt:0.12.21
  allow_failure: false
  when: always
  only:
    - develop
    - master
  artifacts:
    paths:
      - output
  script:
    - cd environment/us-east-1/kubernetes-cluster
    - terragrunt plan

Plan Worload Changes:
  stage: Revision
  image: alpine/terragrunt:0.12.21
  allow_failure: false
  when: always
  only:
    - develop
    - master
  artifacts:
    paths:
      - output
  script:
    - cd environment/us-east-1/basic-deployments
    - terragrunt plan

Apply Cluster:
  stage: Cluster
  image: alpine/terragrunt:0.12.21
  allow_failure: false
  when: manual
  only:
    - develop
    - master
  artifacts:
    paths:
      - output
  script:
    - cd environment/us-east-1/kubernetes-cluster
    - echo "yes" | terragrunt apply


Apply Workload:
  stage: Workload
  image: alpine/terragrunt:0.12.21
  when: on_success
  only:
    - develop
    - master
  cache:
    paths:
      - output
  script:
    - cd environment/us-east-1/basic-deployments
    - echo "yes" | terragrunt apply