---

apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
  namespace: {{ .Release.Namespace }}
data:
  file.system.id: {{ .Values.efs.id }}
  aws.region: {{ .Values.clusterRegion }}
  provisioner.name: {{ .Values.domainName }}/aws-efs
  dns.name: {{ .Values.efs.dnsName }}

---
