---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
spec:
  selector:
    istio: internal-ingressgateway
  servers:
    - port:
        protocol: HTTP
        number: 80
        name: http
      hosts:
        - metrics.{{ $.Values.domainName }}
      tls:
        httpsRedirect: true
    - port:
        protocol: HTTPS
        number: 443
        name: https
      hosts:
        - metrics.{{ $.Values.domainName }}
      tls:
        credentialName: grafana-cert
        mode: SIMPLE
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
spec:
  hosts:
    - metrics.{{ $.Values.domainName }}
  gateways:
    - grafana
  http:
    - match:
      - uri:
          prefix: "/"
      route:
      - destination:
          host: grafana
          port:
            number: 3000
---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: istio-system
  name: grafana-cert
spec:
  commonName: metrics.{{ $.Values.domainName }}
  secretName: grafana-cert
  issuerRef:
    name: dns-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - metrics.{{ $.Values.domainName }}
---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - name: http-web
      targetPort: 3000
      port: 3000
  selector:
    app: grafana