---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
  labels:
    version: v{{ $.Chart.AppVersion }}
    app: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      version: v{{ $.Chart.AppVersion }}
      app: grafana
  template:
    metadata:
      labels:
        version: v{{ $.Chart.AppVersion }}
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:7.1.3
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          env:
            - name: GF_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: host
            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: user
            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: pass
          volumeMounts:
            - name: config-ini
              mountPath: "/etc/grafana/"
            - name: component-dashboard-1
              mountPath: "/var/lib/grafana/dashboards/component/component-1"
            - name: component-dashboard-2
              mountPath: "/var/lib/grafana/dashboards/component/component-2"
            - name: compute-dashboard-1
              mountPath: "/var/lib/grafana/dashboards/compute/compute-1"
            - name: compute-dashboard-2
              mountPath: "/var/lib/grafana/dashboards/compute/compute-2"
            - name: network-dashboard-1
              mountPath: "/var/lib/grafana/dashboards/network/network-1"
            - name: network-dashboard-2
              mountPath: "/var/lib/grafana/dashboards/network/network-2"
            - name: istio-dashboard-1
              mountPath: "/var/lib/grafana/dashboards/istio/istio-1"
            - name: datasources
              mountPath: "/etc/grafana/provisioning/datasources/"
            - name: providers
              mountPath: "/etc/grafana/provisioning/dashboards/"
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: config-ini
          configMap:
            name: grafana-ini
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: providers
          configMap:
            name: grafana-providers
        - name: component-dashboard-1
          configMap:
            name: component-dashboard-1
        - name: component-dashboard-2
          configMap:
            name: component-dashboard-2
        - name: compute-dashboard-1
          configMap:
            name: compute-dashboard-1
        - name: compute-dashboard-2
          configMap:
            name: compute-dashboard-2
        - name: network-dashboard-1
          configMap:
            name: network-dashboard-1
        - name: network-dashboard-2
          configMap:
            name: network-dashboard-2
        - name: istio-dashboard-1
          configMap:
            name: istio-dashboard-1
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data