---

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-iam-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-iam-authenticator
data:
  config.yaml: |
    clusterID: {{ .Values.clusterId }}
    server:
      mapRoles:
      {{- range $value := .Values.authRoles }}
      - roleARN: {{ $value.roleARN }}
        username: {{ $value.username }}
        groups:
        {{- range $group := $value.groups }}
        - {{ $group }}
        {{- end }}
      {{- end }}

---
