---

apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kube-state
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    app: kube-state

---