certIssuer: ${cert_issuer}
domainName: ${domain_name}
serverUrl: ${server_url}
vpnCidr: ${vpn_cidr}
auth:
  clientId: ${client_id}
  secret: ${secret}
smtp:
  from: ${from_adress}
  host: ${smtp_host}
  user: ${smtp_user}
  pass: ${smtp_pass}



