---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: monitoring
      securityContext:
        fsGroup: 9090
      containers:
        - name: prometheus
          image: prom/prometheus:v2.10.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
            - "--storage.tsdb.no-lockfile"
            - "--storage.tsdb.retention.time=10d"
            - "--storage.tsdb.retention.size=7GB"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 150m
              memory: 1024Mi
            limits:
              cpu: 300m
              memory: 2048Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: prometheus-rules
              mountPath: /etc/prometheus-rules
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometeus-data
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
        - name: prometeus-data
          persistentVolumeClaim:
            claimName: prometheus-data
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""

---