---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cluster-metrics
  name: cluster-metrics

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-metrics
subjects:
  - kind: ServiceAccount
    name: cluster-metrics
    namespace: cluster-metrics
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
