---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: cluster-metrics
  name: prometheus-data
spec:
  storageClassName: aws-ebs-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
