{
 "title": "Linkerd Health",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(process_start_time_seconds{control_plane_component!=\"\"}, deployment)"
   },
   { "name": "component", "label": "Component", "query": "label_values(component)" },
   {
    "name": "namespace",
    "label": "Linkerd Namespace",
    "query": "label_values(process_start_time_seconds{control_plane_ns!=\"\"},  control_plane_ns)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Data-Plane Telemetry</span>\n</div>"
  },
  {
   "title": "MEMORY USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2.2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{control_plane_ns=\"$namespace\", job=\"linkerd-proxy\"}",
     "legendFormat": "{{`{{namespace}}`}}/{{`{{pod}}`}}/virtual"
    },
    {
     "expr": "process_resident_memory_bytes{control_plane_ns=\"$namespace\", job=\"linkerd-proxy\"}",
     "legendFormat": "{{`{{namespace}}`}}/{{`{{pod}}`}}/resident"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2.2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{control_plane_ns=\"$namespace\", job=\"linkerd-proxy\"}[20s])) by (namespace, pod)",
     "legendFormat": "{{`{{namespace}}`}}/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "OPEN FILE DESCRIPTORS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2.2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{control_plane_ns=\"$namespace\", job=\"linkerd-proxy\"}",
     "legendFormat": "{{`{{namespace}}`}}/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 9.2 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Traffic</span>\n</div>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11.399999999999999 }, "repeat": "deployment" },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 12.399999999999999 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14.599999999999998 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14.599999999999998 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14.599999999999998 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21.599999999999998 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 22.599999999999998 },
   "content": "<div>\n  de; height:40px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24.799999999999997 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24.799999999999997 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24.799999999999997 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31.799999999999997 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 32.8 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 43 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45.2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45.2 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45.2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52.2 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 53.2 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55.400000000000006 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55.400000000000006 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55.400000000000006 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62.400000000000006 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 63.400000000000006 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65.60000000000001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65.60000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65.60000000000001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72.60000000000001 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 73.60000000000001 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75.80000000000001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod) / sum(irate(response_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75.80000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment, pod)",
     "legendFormat": "po/{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75.80000000000001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p50 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p95 po/{{`{{pod}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment, pod))",
     "legendFormat": "p99 po/{{`{{pod}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82.80000000000001 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 83.80000000000001 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane TCP Metrics</span>\n</div>"
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86.00000000000001 },
   "repeat": "deployment",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 87.00000000000001 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89.20000000000002 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89.20000000000002 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89.20000000000002 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92.00000000000001 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.799999999999997 },
     "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{`{{peer}}`}} {{`{{errno}}`}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}",
       "legendFormat": "{{`{{peer}}`}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23.999999999999996 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=\"$namespace\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94.00000000000001 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 95.00000000000001 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Telemetry</span>\n</div>"
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97.20000000000002 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"linkerd-controller\"}",
     "legendFormat": "{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97.20000000000002 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"linkerd-controller\"}",
     "legendFormat": "{{`{{component}}`}}/resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"linkerd-controller\"}",
     "legendFormat": "{{`{{component}}`}}/virtual"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97.20000000000002 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"linkerd-controller\"}",
     "legendFormat": "{{`{{component}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103.20000000000002 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104.20000000000002 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"linkerd-controller\"}",
     "legendFormat": "{{`{{component}}`}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 111.20000000000002 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Clients/Servers</span>\n</div>"
  },
  {
   "title": "Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113.40000000000002 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_total{job=\"linkerd-controller\"}[30s])) by (component, method, code)",
     "legendFormat": "{{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "HTTP Server Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113.40000000000002 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P50 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P95 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P99 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "HTTP Server Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113.40000000000002 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P50 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P95 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, method, code))",
     "legendFormat": "P99 {{`{{component}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Client Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 120.40000000000002 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_client_requests_total{job=\"linkerd-controller\"}[30s])) by (component, client, method, code)",
     "legendFormat": "{{`{{component}}`}}/{{`{{client}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "HTTP Client Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 120.40000000000002 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, client, method, code))",
     "legendFormat": "P50 {{`{{component}}`}}/{{`{{client}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, client, method, code))",
     "legendFormat": "P95 {{`{{component}}`}}/{{`{{client}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[30s])) by (le, component, client, method, code))",
     "legendFormat": "P99 {{`{{component}}`}}/{{`{{client}}`}}/{{`{{method}}`}}/{{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Client In-Flight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 120.40000000000002 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_client_in_flight_requests{job=\"linkerd-controller\"}) by (component, client)",
     "legendFormat": "{{`{{component}}`}}/{{`{{client}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127.40000000000002 }, "repeat": "component" },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 128.40000000000003 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 130.60000000000002 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 130.60000000000002 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 130.60000000000002 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137.60000000000002 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 138.60000000000002 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 140.8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 140.8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 140.8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147.8 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 148.8 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 151 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 151 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 159 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 161.2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 161.2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 161.2 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168.2 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 169.2 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 171.39999999999998 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 171.39999999999998 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 171.39999999999998 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178.39999999999998 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 179.39999999999998 },
   "content": "<div>\n  &nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>"
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 181.59999999999997 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{`{{component}}`}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "alloc rate/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{`{{component}}`}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 181.59999999999997 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{`{{component}}`}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{`{{component}}`}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 181.59999999999997 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "sent/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[30s])",
     "legendFormat": "received/{{`{{component}}`}}/{{`{{grpc_method}}`}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188.59999999999997 } }
 ]
}