---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ $.Release.Namespace }}
  name: openvpn
spec:
  selector:
    istio: istio-ingressgateway
  servers:
    - hosts:
        - vpn.{{ $.Values.domainName }}
      port:
        protocol: TCP
        number: 1194
        name: tcp
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ $.Release.Namespace }}
  name: openvpn
spec:
  gateways:
    - openvpn
  hosts:
    - vpn.{{ $.Values.domainName }}
  tcp:
    - match:
        - port: 1194
      route:
        - destination:
            host: openvpn
            port:
              number: 1194
---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: openvpn
  labels:
    app: openvpn
spec:
  ports:
    - name: tcp-server
      targetPort: 1194
      port: 1194
  selector:
    app: openvpn