---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ $.Release.Namespace }}
  name: openvpn
  labels:
    version: v{{ $.Chart.AppVersion }}
    app: openvpn
spec:
  serviceName: openvpn
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        version: v{{ $.Chart.AppVersion }}
        app: openvpn
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.metal-city.ru/scope
                    operator: In
                    values:
                      - commom
      containers:
        - name: openvpn
          image: jfelten/openvpn-docker:1.1.0
          imagePullPolicy: IfNotPresent
          command: ["/etc/openvpn/setup/configure.sh"]
          ports:
            - name: tcp-server
              containerPort: 1194
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/openvpn/setup
              name: openvpn
              readOnly: false
            - mountPath: /etc/openvpn/certs
              name: certs
              readOnly: false
      volumes:
        - name: openvpn
          configMap:
            name: openvpn-config
            defaultMode: 0775
        - name: certs
          persistentVolumeClaim:
            claimName: openvpn-data