---

apiVersion: v1
kind: Service
metadata:
  namespace: cluster-metrics
  name: prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports: 
    - targetPort: 9090
      port: 9090
  selector:
    app: prometheus

---
