---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cluster-metrics
  name: alertmanager
data:
  config.yml: |-
    global:
      smtp_smarthost: ${smtp_host}
      smtp_auth_username: ${smtp_user}
      smtp_auth_password: ${smtp_pass}
      smtp_from: ${from_adress}
      resolve_timeout: 5m
      slack_api_url: ${slack_hook}

    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m  
      receiver: default 
      routes:
      - match:
          team: devops
        receiver: devops
        continue: true 
      - match: 
          team: dev
        receiver: dev
        continue: true

    receivers:
    - name: 'default'

    - name: 'devops'
      slack_configs:
      - channel: '${slack_channel}'
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - \`{{ .Labels.severity }}\`
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* \`{{ .Value }}\`
            {{ end }}
          {{ end }}

    - name: 'dev'
      slack_configs:
      - channel: '${slack_channel}'
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - \`{{ .Labels.severity }}\`
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* \`{{ .Value }}\`
            {{ end }}
          {{ end }}

---
