---

apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - targetPort: 9093
      port: 9093
  selector:
    app: alertmanager

---