---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager
data:
  config.yml: |-
    global:
      slack_api_url: {{ $.Values.slack.hook }}
      resolve_timeout: 5m
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      receiver: 'slack'
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: 'null'
      - match:
        receiver: 'slack'
        continue: true
    receivers:
    - name: 'null'
    - name: 'slack'
      slack_configs:
      - channel: #{{ $.Values.slack.channel }}
        send_resolved: true
    {{ $.Files.Get "static-files/slack-template.yaml" | nindent 8 }}