---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      receiver: 'alertmananger-bot'
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: 'null'
      - match:
        receiver: 'alertmananger-bot'
        continue: true
    receivers:
    - name: 'null'
    - name: 'alertmananger-bot'
      webhook_configs:
      - send_resolved: true
        url: 'http://alertmanager-bot:8080'