---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager
  labels:
    version: v{{ $.Chart.AppVersion }}
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v{{ $.Chart.AppVersion }}
      app: alertmanager
  template:
    metadata:
      labels:
        version: v{{ $.Chart.AppVersion }}
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.20.0
        resources:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
            cpu: 50m
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
          - name: http-metrics
            containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-data
          mountPath: /alertmanager
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager
      - name: alertmanager-data
        emptyDir: {}