---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager
  labels:
    version: v{{ $.Chart.AppVersion }}
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        version: v{{ $.Chart.AppVersion }}
        app: alertmanager
    spec:
      priorityClassName: system-cluster-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.metal-city.ru/scope
                    operator: In
                    values:
                      - commom
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.21.0
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 30m
            memory: 64Mi
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
          - name: http-metrics
            containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-data
          mountPath: /alertmanager
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager
      - name: alertmanager-data
        emptyDir: {}