---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: alertmanager
spec:
  ports:
    - name: http-metrics
      targetPort: 9093
      port: 9093
  selector:
    app: alertmanager