---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ $.Release.Namespace }}
  name: prometheus-data
spec:
  storageClassName: aws-ebs-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi