---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-config
data:
  server-root-url: ${server_url}
  smtp-from-adress: ${from_adress}
  smtp-enabled: "true"
  auth-anonymous-enabled: "false"
  auth-basic-enabled: "true"

---