---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-config
data:
  server-root-url: ${server_url}
  server-domain: ${domain_name}
  smtp-from-address: ${from_adress}
  smtp-enabled: "true"
  auth-anonymous-org-name: ${cluster_name}
  auth-anonymous-enabled: "false"
  auth-basic-enabled: "true"

---