{
 "title": "Linkerd Job",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(process_start_time_seconds{k8s_job!=\"\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, k8s_job)"
   },
   {
    "name": "inbound",
    "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_k8s_job=\"$job\"}, k8s_job)"
   },
   {
    "name": "outbound",
    "query": "label_values(request_total{namespace=\"$namespace\", k8s_job=\"$job\"}, dst_k8s_job)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 }, "content": "<br/>" },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2.4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) / sum(irate(response_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "INBOUND JOBS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{dst_namespace=\"$namespace\", k8s_job!=\"\", dst_k8s_job!=\"\", dst_k8s_job=\"$job\", direction=\"outbound\"}) by (namespace, k8s_job))"
    }
   ]
  },
  {
   "title": "OUTBOUND JOBS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}) by (namespace, dst_k8s_job))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 6.4 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) by (k8s_job) / sum(irate(response_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) by (k8s_job)",
     "legendFormat": "job/{{k8s_job}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\", tls=\"true\"}[30s])) by (k8s_job)",
     "legendFormat": "🔒job/{{k8s_job}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\", tls!=\"true\"}[30s])) by (k8s_job)",
     "legendFormat": "job/{{k8s_job}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) by (le, k8s_job))",
     "legendFormat": "p50 job/{{k8s_job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) by (le, k8s_job))",
     "legendFormat": "p95 job/{{k8s_job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}[30s])) by (le, k8s_job))",
     "legendFormat": "p99 job/{{k8s_job}}"
    }
   ]
  },
  {
   "title": "Inbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15.600000000000001 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16.6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16.6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16.6 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16.6 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 17.6 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND JOBS</span>\n</div>"
  },
  {
   "title": "job/$inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19.8 },
   "repeat": "inbound",
   "collapsed": true,
   "panels": [
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22.8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (k8s_job, pod) / sum(irate(response_total{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (k8s_job, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22.8 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\", tls=\"true\"}[30s])) by (k8s_job, pod)",
       "legendFormat": "🔒po/{{pod}}"
      },
      {
       "expr": "sum(irate(request_total{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\", tls!=\"true\"}[30s])) by (k8s_job, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22.8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (le, k8s_job))",
       "legendFormat": "P50 job/{{k8s_job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (le, k8s_job))",
       "legendFormat": "P95 job/{{k8s_job}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{k8s_job!=\"\", k8s_job=\"$inbound\", dst_namespace=\"$namespace\", dst_k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (le, k8s_job))",
       "legendFormat": "P99 job/{{k8s_job}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20.8 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.8 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (dst_k8s_job) / sum(irate(response_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "job/{{dst_k8s_job}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "🔒job/{{dst_k8s_job}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "job/{{dst_k8s_job}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}[30s])) by (le, dst_k8s_job))",
     "legendFormat": "P95 job/{{dst_k8s_job}}"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 33 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND JOBS</span>\n</div>"
  },
  { "title": "job/$outbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35.2 }, "repeat": "outbound" },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38.2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\"}[30s])) by (dst_k8s_job) / sum(irate(response_total{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "job/{{dst_k8s_job}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38.2 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "🔒job/{{dst_k8s_job}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_k8s_job)",
     "legendFormat": "job/{{dst_k8s_job}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38.2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_k8s_job))",
     "legendFormat": "P50 job/{{dst_k8s_job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_k8s_job))",
     "legendFormat": "P95 job/{{dst_k8s_job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", k8s_job=\"$job\", dst_k8s_job=\"$outbound\", direction=\"outbound\"}[30s])) by (le, dst_k8s_job))",
     "legendFormat": "P99 job/{{dst_k8s_job}}"
    }
   ]
  }
 ]
}
{
 "title": "Linkerd Service",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(request_total, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(request_total{namespace=\"$namespace\"}, dst_service)"
   },
   {
    "name": "inbound",
    "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_service=\"$service\"}, deployment)"
   },
   {
    "name": "outbound",
    "query": "label_values(request_total{namespace=\"$namespace\", deployment=\"$deployment\"}, dst_deployment)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 }, "content": "<br/>" },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2.4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) / sum(irate(response_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 6.4 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP-LINE TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service) / sum(irate(response_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service)",
     "legendFormat": "svc/{{dst_service}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_service)",
     "legendFormat": "🔒svc/{{dst_service}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_service)",
     "legendFormat": "svc/{{dst_service}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service))",
     "legendFormat": "p50 svc/{{dst_service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service))",
     "legendFormat": "p95 svc/{{dst_service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service))",
     "legendFormat": "p99 svc/{{dst_service}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 15.600000000000001 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY DEPLOYMENT</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17.8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service, deployment) / sum(irate(response_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service, deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17.8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_service, deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_service, deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17.8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service, deployment))",
     "legendFormat": "P95 deploy/{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 24.8 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY POD</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service, pod) / sum(irate(response_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (dst_service, pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls=\"true\"}[30s])) by (dst_service, pod)",
     "legendFormat": "🔒po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls!=\"true\"}[30s])) by (dst_service, pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[30s])) by (le, dst_service, pod))",
     "legendFormat": "P95 po/{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Linkerd Top Line",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(process_start_time_seconds, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(process_start_time_seconds{deployment!=\"\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "GLOBAL SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=~\"$deployment\"}[30s])) / sum(irate(response_total{deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "GLOBAL REQUEST VOLUME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment=~\"$deployment\"}[30s]))"
    }
   ]
  },
  {
   "title": "NAMESPACES MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=~\"$namespace\"}) by (namespace))"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(request_total{namespace=~\"$namespace\"}) by (namespace, deployment))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 7 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP LINE</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9.2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (namespace) / sum(irate(response_total{namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (namespace)",
     "legendFormat": "ns/{{namespace}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9.2 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", direction=\"inbound\", tls=\"true\"}[30s])) by (namespace)",
     "legendFormat": "🔒ns/{{namespace}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=~\"$namespace\", direction=\"inbound\", tls!=\"true\"}[30s])) by (namespace)",
     "legendFormat": "ns/{{namespace}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9.2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=~\"$namespace\", direction=\"inbound\"}[30s])) by (le, namespace))",
     "legendFormat": "p95 ns/{{namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 16.2 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>NAMESPACES</span>\n</div>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18.4 }, "repeat": "namespace" },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21.4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST VOLUME",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21.4 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", direction=\"inbound\", tls=\"true\"}[30s])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", direction=\"inbound\", tls!=\"true\"}[30s])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21.4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\"}[30s])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    }
   ]
  }
 ]
}