---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-source
data:
  prometheus-datasource.json: |
    {
      "name": "prometheus",
      "type": "prometheus",
      "url": "http://prometheus:9090",
      "access": "proxy",
      "basicAuth": false
    }

---