---

apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: {{ .Release.Namespace }}
  labels:
    app: openvpn
spec:
  ports:
    - name: openvpn
      port: 1194
      targetPort: 1194
      protocol: TCP
  selector:
    app: openvpn

---
