---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: {{ $.Release.Namespace }}
data:
  grafana.ini: |
    [auth.google]
    enabled = true
    client_id = {{ $.Values.auth.clientId }}
    client_secret = {{ $.Values.auth.secret }}
    scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    auth_url = https://accounts.google.com/o/oauth2/auth
    token_url = https://accounts.google.com/o/oauth2/token
    allowed_domains = {{ $.Values.domainName }}
    allow_sign_up = true
    [server]
    root_url = {{ $.Values.serverUrl }}
    domain = {{ $.Values.domainName }}
    [smtp]
    from_address = {{ $.Values.smtp.from }}
    enabled = true
    [auth.basic]
    enabled = false
    [auth.anonymous]
    enabled = false
    [auth]
    disable_login_form = true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ $.Release.Namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: prometheus
      type: prometheus
      url: http://prometheus:9090
      version: 1

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
  namespace: {{ $.Release.Namespace }}
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: true
      editable: true
      folder: "Ingress"
      name: ingress
      options:
        path: /var/lib/grafana/dashboards/ingress
      orgId: 1
      type: file
    - disableDeletion: true
      editable: true
      folder: "Cluster"
      name: cluster
      options:
        path: /var/lib/grafana/dashboards/cluster
      orgId: 1
      type: file
    - disableDeletion: true
      editable: true
      folder: "Linkerd"
      name: linkerd-first
      options:
        path: /var/lib/grafana/dashboards/linkerd-first
      orgId: 1
      type: file
    - disableDeletion: true
      editable: true
      folder: "Linkerd"
      name: linkerd-second
      options:
        path: /var/lib/grafana/dashboards/linkerd-second
      orgId: 1
      type: file
    - disableDeletion: true
      editable: true
      folder: "Linkerd"
      name: linkerd-second
      options:
        path: /var/lib/grafana/dashboards/linkerd-third
      orgId: 1
      type: file

---
