---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager-bot
  labels:
    app: alertmanager-bot
data:
  admin: {{ $.Values.telegram.admin }}
  token: {{ $.Values.telegram.token }}