---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: alertmanager-bot
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: alertmanager-bot
spec:
  ports:
    - name: http-metrics
      targetPort: 8080
      port: 8080
  selector:
    app: alertmanager-bot