---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:6.1.4
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: GF_SERVER_ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: server-root-url
            - name: GF_SERVER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: server-domain
            - name: GF_AUTH_BASIC_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: auth-basic-enabled
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: auth-anonymous-org-name
            - name: GF_AUTH_ANONYMOUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: auth-anonymous-enabled
            - name: GF_SMTP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: smtp-enabled
            - name: GF_SMTP_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: smtp-from-address
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: password
            - name: GF_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: host
            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: user
            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: pass
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""

---