---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: monitoring
  name: grafana-data
spec:
  storageClassName: aws-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---