---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana-smtp
data:
  host: {{ $.Values.smtp.host }}
  user: {{ $.Values.smtp.user }}
  pass: {{ $.Values.smtp.host }}

---
