---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        protocol: HTTP
        number: 80
        name: http
      hosts:
        - metrics.{{ $.Values.domainName }}
    - port:
        protocol: HTTPS
        number: 443
        name: https
      hosts:
        - metrics.{{ $.Values.domainName }}
      tls:
        credentialName: grafana-cert
        mode: SIMPLE

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
spec:
  gateways:
    - grafana
  hosts:
    - metrics.{{ $.Values.domainName }}
  http:
    - match:
       - port: 443
      route:
        - destination:
            host: grafana
            port:
              number: 3000

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana-cert
spec:
  commonName: metrics.{{ $.Values.domainName }}
  secretName: grafana-cert
  issuerRef:
    name: dns-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - metrics.{{ $.Values.domainName }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
spec:
  ports:
    - targetPort: 3000
      port: 3000
  selector:
    app: grafana

---
