---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ $.Release.Namespace }}
  name: grafana
  labels:
    app: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:6.6.2
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 518Mi
          env:
            - name: GF_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: host
            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: user
            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp
                  key: pass
          volumeMounts:
            - name: config-ini
              mountPath: "/etc/grafana/"
            - name: cluster-dashboard
              mountPath: "/var/lib/grafana/dashboards/cluster"
#            - name: istio-dashboard-first
#              mountPath: "/var/lib/grafana/dashboards/istio-first"
#            - name: istio-dashboard-second
#              mountPath: "/var/lib/grafana/dashboards/istio-second"
            - name: datasources
              mountPath: "/etc/grafana/provisioning/datasources/"
            - name: providers
              mountPath: "/etc/grafana/provisioning/dashboards/"
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: config-ini
          configMap:
            name: grafana-ini
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: providers
          configMap:
            name: grafana-providers
        - name: cluster-dashboard
          configMap:
            name: cluster-dashboard
#        - name: istio-dashboard-first
#          configMap:
#            name: istio-dashboard-first
#        - name: istio-dashboard-second
#          configMap:
#            name: istio-dashboard-second
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data

---
