---

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-iam-authenticator
  namespace: kube-system
  labels:
    app: aws-iam-authenticator
data:
  config.yaml: |
    clusterID: ${cluster_id}
    server:
      mapRoles:
      - roleARN: ${admin_role}
        username: kubernetes-admin
        groups:
        - system:masters

---