---

apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
    - targetPort: 9100
      port: 9100
  selector:
    app: node-exporter

---