---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: cert-manager
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9402'
  labels:
    app: cert-manager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      targetPort: 9402
      port: 9402
  selector:
    app: cert-manager
---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: cert-manager-webhook
  labels:
    app: cert-manager-webhook
spec:
  type: ClusterIP
  ports:
    - name: client
      targetPort: 10250
      port: 443
  selector:
    app: cert-manager-webhook